# Production image for the Express backend (backend/server.js).
# Build context is the repository root -- see ../.dockerignore.

FROM node:20-alpine

ENV NODE_ENV=production

WORKDIR /app

# Install dependencies first so this layer is cached unless the lockfile moves.
# --omit=dev drops nodemon; the app only needs the runtime dependencies.
# The lock files in this repo are generated by npm 11 (the host toolchain).
# node:20-alpine ships npm 10, which rejects them with
# "npm ci can only install packages when your package.json and
# package-lock.json are in sync ... Missing: yaml@2.9.1 from lock file".
# Matching the host's npm here is less invasive than regenerating the lock
# files, and keeps Node 20 for the runtime, which is what CRA 5 expects.
RUN npm install -g npm@11

COPY backend/package.json backend/package-lock.json ./
# This network drops TLS connections under npm's default 15-way parallelism
# (seen as ERR_SSL_CIPHER_OPERATION_FAILED / "tls: bad record MAC"). Fewer
# concurrent sockets plus retries makes the install survive it.
RUN npm config set fetch-retries 5  && npm config set fetch-retry-maxtimeout 120000  && npm config set maxsockets 3

RUN npm ci --omit=dev

COPY backend/ ./

# server.js reads process.env.PORT (default 5005) and process.env.HOST.
# HOST=0.0.0.0 is required in a container: the original code bound to
# 'localhost', which inside a container means the container's own loopback and
# would make the service unreachable from nginx. See the HOST change in
# backend/server.js.
ENV PORT=5005
ENV HOST=0.0.0.0

EXPOSE 5005

# Run as the image's unprivileged user rather than root.
USER node

CMD ["node", "server.js"]
