# Production image for the Create React App frontend.
#
# Two stages: build the static bundle with Node, then serve it with nginx.
# The final image contains no Node runtime and no source code.
#
# IMPORTANT: Create React App inlines REACT_APP_* variables at BUILD time --
# they are not read at runtime. They therefore arrive as build args, and
# anything passed here ends up readable in the browser bundle. Only the public
# Firebase web-app identifiers belong here; never DB credentials, JWT_SECRET or
# the Firebase service account.

# ---------- stage 1: build ----------
FROM node:20-alpine AS build

WORKDIR /app

# The lock files in this repo are generated by npm 11 (the host toolchain).
# node:20-alpine ships npm 10, which rejects them with
# "npm ci can only install packages when your package.json and
# package-lock.json are in sync ... Missing: yaml@2.9.1 from lock file".
# Matching the host's npm here is less invasive than regenerating the lock
# files, and keeps Node 20 for the runtime, which is what CRA 5 expects.
RUN npm install -g npm@11

COPY frontend/package.json frontend/package-lock.json ./
# This network drops TLS connections under npm's default 15-way parallelism
# (seen as ERR_SSL_CIPHER_OPERATION_FAILED / "tls: bad record MAC"). Fewer
# concurrent sockets plus retries makes the install survive it.
RUN npm config set fetch-retries 5  && npm config set fetch-retry-maxtimeout 120000  && npm config set maxsockets 3

RUN npm ci

COPY frontend/ ./

# Left empty on purpose: frontend/src/config/api.js falls back to '' and every
# call is written as `${API_BASE_URL}/api/...`, so an empty base produces the
# relative path /api/... -- same-origin through nginx. Setting an absolute URL
# here would expose the backend host to the browser and break the single-origin
# design.
ARG REACT_APP_API_URL=""

ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ARG REACT_APP_FIREBASE_APP_ID

ENV REACT_APP_API_URL=$REACT_APP_API_URL \
    REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY \
    REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN \
    REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID \
    REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET \
    REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID \
    REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID \
    CI=true \
    GENERATE_SOURCEMAP=false

RUN npm run build

# ---------- stage 2: serve ----------
FROM nginx:1.27-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY production/nginx/frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
